name: lhy_music
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1
  - ffmpeg=6.1.1
  - av=11.0.0
  - pip
  - pip:
      - git+https://github.com/facebookresearch/audiocraft.git
      - numpy<2.0.0
      - soundfile
      - tqdm
      - transformers>=4.31.0,<4.36.0
      - huggingface_hub<1.0.0
      - gradio==6.14.0
